# Generated by Django 4.1 on 2022-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlName',
            field=models.CharField(default=1, max_length=250, verbose_name='Имя ссылки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='urlName',
            field=models.CharField(default=1, max_length=250, verbose_name='Имя ссылки'),
            preserve_default=False,
        ),
    ]
