# Generated by Django 4.1 on 2022-09-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_urlname_product_urlname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='urlName',
        ),
    ]
