# Generated by Django 4.1 on 2022-10-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_vieweditems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vieweditems',
            options={'ordering': ['-title'], 'verbose_name': 'Количесто просмотров товаров', 'verbose_name_plural': 'Количесто просмотров товара'},
        ),
    ]
