# Generated by Django 4.1 on 2022-11-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='category',
            field=models.CharField(max_length=250, verbose_name='Категория'),
        ),
    ]
