# Generated by Django 4.1 on 2022-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_searchquery_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='sort_by',
            field=models.CharField(blank=True, max_length=250, verbose_name='Сортировать по'),
        ),
    ]
