# Generated by Django 4.1 on 2022-11-02 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_searchquery_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Опубликован'),
            preserve_default=False,
        ),
    ]
