# Generated by Django 4.1 on 2022-11-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_searchquery_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vieweditems',
            name='sort_by',
            field=models.CharField(default='not', max_length=250, verbose_name='Упорядочить по'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='sort_by',
            field=models.CharField(default='not', max_length=250, verbose_name='Упорядочить по'),
        ),
    ]
