# Generated by Django 4.1 on 2022-11-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_vieweditems_sort_by_alter_searchquery_sort_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vieweditems',
            name='sort_by',
        ),
        migrations.AddField(
            model_name='product',
            name='sort_by',
            field=models.CharField(default='not', max_length=250, verbose_name='Упорядочить по'),
        ),
    ]
