# Generated by Django 4.1 on 2022-11-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_vieweditems_sort_by_product_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='diameter',
            field=models.CharField(default='not', max_length=250, verbose_name='Диаметр'),
        ),
        migrations.AddField(
            model_name='product',
            name='hdd_type',
            field=models.CharField(default='not', max_length=250, verbose_name='Тип жёского диска'),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default='not', max_length=250, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default='not', max_length=250, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(default='not', max_length=250, verbose_name='Сезон'),
        ),
        migrations.AddField(
            model_name='product',
            name='tyre_section_width',
            field=models.CharField(default='not', max_length=250, verbose_name='Ширина профиля шины'),
        ),
        migrations.AddField(
            model_name='product',
            name='vram',
            field=models.CharField(default='not', max_length=250, verbose_name='Видеопамять'),
        ),
    ]
