# Generated by Django 4.1 on 2022-11-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_diameter_product_hdd_type_product_processor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tyre_section_height',
            field=models.CharField(default='not', max_length=250, verbose_name='Высота профиля шины'),
        ),
    ]
