# Generated by Django 4.1 on 2022-11-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_product_search_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='user',
            field=models.CharField(default='---', max_length=15, verbose_name='Пользователь'),
        ),
    ]
