# Generated by Django 4.1 on 2022-10-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0002_productinbasket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product',
            field=models.CharField(default=True, max_length=500, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='user',
            field=models.CharField(default=True, max_length=15, verbose_name='Пользователь'),
        ),
    ]
