# Generated by Django 4.1 on 2022-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0004_alter_productinbasket_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='price_per_item',
            field=models.IntegerField(default=0, verbose_name='Цена за товар'),
        ),
        migrations.AlterField(
            model_name='productinbasket',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Итоговая цена'),
        ),
    ]
