# Generated by Django 4.1 on 2022-10-12 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0005_alter_productinbasket_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, upload_to='images/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
