# Generated by Django 4.1 on 2022-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0013_alter_productinbasket_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='---', max_length=15, verbose_name='Пользователь')),
                ('image', models.ImageField(blank=True, max_length=1000, upload_to='', verbose_name='Фото')),
                ('product', models.CharField(default='---', max_length=500, verbose_name='Товар')),
                ('price_per_item', models.IntegerField(default=0, verbose_name='Цена за товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Выборка покупателя',
                'verbose_name_plural': 'Выборка покупателя',
            },
        ),
    ]
