# Generated by Django 4.1 on 2022-10-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0014_userselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
