# Generated by Django 4.1 on 2022-10-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0015_userselection_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(default='---', max_length=1500, verbose_name='Идентификатор заказа')),
                ('user', models.CharField(default='---', max_length=15, verbose_name='Пользователь')),
                ('image', models.ImageField(blank=True, max_length=1000, upload_to='', verbose_name='Фото')),
                ('title', models.CharField(default='---', max_length=500, verbose_name='Товар')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за товар')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Оплаченный товар',
                'verbose_name_plural': 'Оплаченные товары',
            },
        ),
    ]
