# Generated by Django 4.1 on 2022-10-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userEnvironment', '0016_purchaseditemsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userselection',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
